### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/numba-feedstock#1]
Currently the test suite is not run in parallel and it takes a fair bit of time to run. Would be good if we could run the test suite in parallel so that it could speed up that portion a bit. According to the docs, one can do this with `python -m numba.runtests -m`. Not sure if there is a way to tell the test runner how many cores it can use, which we may want to do to avoid oversubscribing the hardware given to us for the CI job.

**Comment by jakirkham** [comment]
Raised issue ( https://github.com/numba/numba/issues/2940 ) upstream about constraining the number of processes used for testing.

**Comment by marcelotrevisani** [comment]
I think this issue was addressed right!?
I am going to close it then. If not please feel free to reopen it
:)
