### ISSUE TITLE
Numba: Support CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/numba-feedstock#112]
Will depend on a new release of Numba with these changes:

* [x] https://github.com/numba/numba/pull/7255

Also depends on the new CUDA packages ( https://github.com/conda-forge/staged-recipes/issues/21382 )

**Comment by jakirkham** [comment]
@gmarkall, can you please let me know if there are any other changes we should be tracking for CUDA 12 support in Numba?

**Comment by gmarkall** [comment]
This PR: https://github.com/numba/numba/pull/8290 is the one that changed Numba such that CUDA 12 would work with it (but it isn't explicitly mentioned in the PR).

CUDA 12 support is independent of numba/numba#7255 - that PR is only for supporting packages from the NVIDIA Conda channel and the layout used in the Conda-forge CUDA 12 packages, but Numba `main` works fine with CUDA 12 from other sources (e.g. a system-wide installation, or a toolkit in a location specified with `CUDA_HOME`).

**Comment by jakirkham** [comment]
Sounds like an RC is coming soon ( https://github.com/numba/numba/issues/8304#issuecomment-1480200472 ). Would be good to test things out with the RC

**Comment by jakirkham** [comment]
There is now a [0.57.0rc1 tag on GH]( https://github.com/numba/numba/releases/tag/0.57.0rc1 )

**Comment by jakirkham** [comment]
FWIW Graham and I have been working together to test the RC package from the `numba` channel with the `conda-forge` CTK 12 packages (and the `nvidia` channel ones). So far things seem to be working.

Will probably run a few more tests at least until related CTK 12 changes settle. Though am not expecting any major surprises at this point. If anything comes up it is almost certainly on conda-forge packaging side, which we can work through.

Will keep this open until the 0.57.0 release ships.

**Comment by jakirkham** [comment]
The bot just opened PR ( https://github.com/conda-forge/numba-feedstock/pull/115 ) to upgrade to  `0.57.0`

**Comment by jakirkham** [comment]
As follow up here, would be good to update the Numba docs on best practices with CUDA 12 ( https://github.com/numba/numba/issues/9045 )
