### ISSUE TITLE
Update numba for condage forge

### ISSUE THREAD

**Issue by hxawax** [conda-forge/numba-feedstock#116]
### Comment:

Hello, 

I noticed that numba's version on conda-forge repo is one version behind, still 0.56 when the 0.57 is out on other channels. 
This participates in breaking Python 3.11 environment dependency for some packages that have already been updated.
https://anaconda.org/conda-forge/numba
https://anaconda.org/numba/numba

I'm not 100% here is a good place to ask for this, 
but thanks for your work anyway

**Comment by theXYZT** [comment]
See pull request https://github.com/conda-forge/numba-feedstock/pull/115
