### ISSUE TITLE
Should we enable osx-arm64 testing

### ISSUE THREAD

**Issue by gmarkall** [conda-forge/numba-feedstock#143]
### Comment:

I notice that tests aren't run for osx-arm64, and I'm wondering if that's because they would always have crashed before numba/numba#8567 got fixed. They shouldn't crash anymore, so should tests be run on osx-arm64 as well?

**Comment by jakirkham** [comment]
As we lack hardware to run CI, we can't test it unfortunately

When that changes, we can revisit

xref: https://github.com/conda-forge/conda-forge.github.io/issues/1781

**Comment by gmarkall** [comment]
Ah, thanks for the clarification - I hadn't realised this wasn't a Numba-specific issue - will close this rather than adding to the noise :-)
