### ISSUE TITLE
No build for 0.60.0 available

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/numba-feedstock#147]
### Comment:

I just wanted to upgrade to NumPy 2.0 but numba hold me back. The feedstock seems to be fine, https://github.com/conda-forge/numba-feedstock/pull/146 got merged but no build can be found in https://anaconda.org/conda-forge/numba may because of `[ci skip]` in the commit message?

**Comment by henryiii** [comment]
I removed a comment on main, let’s see if that rebuilds and pushes.

**Comment by m-rossi** [comment]
Looks good, first packages are rolling in, thanks!
