### ISSUE TITLE
Reenable tbb on macOS? (and maybe windows?)

### ISSUE THREAD

**Issue by seibert** [conda-forge/numba-feedstock#43]
I just discovered while helping someone troubleshoot problem with the `numba` package from conda-forge that TBB is disabled for non-Linux platforms:

https://github.com/conda-forge/numba-feedstock/blob/master/recipe/meta.yaml#L38

It seems that the origin of this exclusion was a workaround for https://github.com/conda-forge/tbb-feedstock/issues/42#issuecomment-427921828, which may not apply anymore?

(I will open a PR to make the change, but wanted to note the issue while fresh off this debug session.)

**Comment by henryiii** [comment]
10.9 is still the default, with upgrades listed as a last resort: https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

**Comment by henryiii** [comment]
I don't see any such workaround in the TBB formula, though.

**Comment by henryiii** [comment]
Looks like 19.2+ should be fine, AFAICT.
