### ISSUE TITLE
For the next build testing needs to use a newer TBB

### ISSUE THREAD

**Issue by stuartarchibald** [conda-forge/numba-feedstock#63]
- ~[ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.~ N/A

Issue:

For the next release/build it would be good to address this https://github.com/conda-forge/numba-feedstock/pull/62#discussion_r534509046 such that the tests declare that they require the minimum supported version of TBB.

<br/>
Environment (<code>conda list</code>):

N/A

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

N/A

**Comment by henryiii** [comment]
Doesn’t need a new build number so could be done any time.
