### ISSUE TITLE
Rerun Travis

### ISSUE THREAD

**Issue by henryiii** [conda-forge/numba-feedstock#71]
Rerun Travis when this is fixed:

Yeah that is a known issue ( https://github.com/conda-forge/status/issues/110 )

_Originally posted by @jakirkham in https://github.com/conda-forge/numba-feedstock/issues/69#issuecomment-798799619_

**Comment by henryiii** [comment]
Done. :)

**Comment by jakirkham** [comment]
Was looking to do that this morning, but seems you beat me to it 😄
